### ISSUE TITLE
Midterm Feeback

### ISSUE THREAD

**Issue by Devaio** [andrewbrovan/Midterm_Project#1]
Great app - let me know when it can replace the calculator on my phone!
- Great job implementing Order of Operations
    - Easy to do on paper, much more difficult when you have to check through a whole string and get it organized in code!
- Complex logic for order of operations and expression simplification
    - Really like the step by step printout it does!
- Simple and extremely functional UI
    - No muss, no fuss

**Comment by andrewbrovan** [comment]
Thanks!
